export const SET_TROUBLES = 'SET_TROUBLES';
export const FETCH_TROUBLES_FAILED = 'FETCH_TROUBLES_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const STORE_PIN_START = 'STORE_PIN_START';
export const STORE_PIN_SUCCESS = 'STORE_PIN_SUCCESS';
export const STORE_PIN_FAIL = 'STORE_PIN_FAIL';
export const FETCH_PIN_START = 'FETCH_PIN_START';
export const FETCH_PIN_SUCCESS = 'FETCH_PIN_SUCCESS';
export const FETCH_PIN_FAIL = 'FETCH_PIN_FAIL';